-- WEBCRM — schema PostgreSQL (Supabase), portado de schema.sql (SQLite)
-- Convenções mantidas do original: datas em TEXT ISO-8601 (YYYY-MM-DD ou YYYY-MM-DD HH:MM:SS);
-- CNPJ em TEXT. Dinheiro (era REAL no SQLite) virou NUMERIC aqui -- REAL é ponto flutuante,
-- inadequado pra valores monetários.
--
-- Diferenças de tradução em relação ao schema.sql original (ver STATUS.md / plano de migração
-- pra contexto completo):
--   - INTEGER PRIMARY KEY (rowid-alias do SQLite) -> INTEGER GENERATED BY DEFAULT AS IDENTITY.
--     "BY DEFAULT" (não "ALWAYS") de propósito: a migração de dados (Fase 7) precisa inserir
--     linhas com PK explícito (preservando os IDs do SQLite de origem) sem precisar de
--     "OVERRIDING SYSTEM VALUE" em todo INSERT -- com ALWAYS isso seria obrigatório.
--   - REAL (dinheiro) -> NUMERIC(14,2). REAL (quantidade/hora/índice) -> NUMERIC com escala
--     menor, ver comentário em cada coluna.
--   - Colunas GENERATED ... VIRTUAL (SQLite) -> GENERATED ALWAYS AS (...) STORED aqui, com
--     funções trocadas por equivalentes Postgres (instr->position, substr->substring).
--     5 das 6 colunas geradas do original permaneceram declarativas (pessoa_grupo,
--     pessoa_whatsapp, feriasm_indice, crono_grp_tpc, cart_nome_plan_analitica -- esta última
--     resolvida via substring puro, sem strftime/to_char, que não são IMMUTABLE). A exceção é
--     feriasm_prazo: dependia de julianday (diferença de datas), e o cast texto->date exigido
--     pra isso não é IMMUTABLE no Postgres (depende do DateStyle da sessão) -- essa coluna virou
--     comum, computada em código de aplicação (ver comentário na própria coluna, abaixo).
--   - usuarios.user_mail vira `citext` (case-insensitive nativo) -- substitui o
--     `COLLATE NOCASE` usado nas queries de login (auth.ts/usuarios.ts), e fecha uma race
--     condition de unicidade que existia só em nível de app.
--   - FK forward-reference corrigida: list_resp_crono agora é declarada antes de crono
--     (no SQLite original, a ordem inversa era tolerada; Postgres exige a tabela referenciada
--     já existir no momento do CREATE TABLE).
--   - PRAGMA foreign_keys -- removido (Postgres sempre aplica FK).

CREATE EXTENSION IF NOT EXISTS citext;

-- ============================================================
-- TABELAS DE DIMENSÃO (mestre / referência)
-- ============================================================

CREATE TABLE grupos_econ (
    grp_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grp_nome    TEXT NOT NULL
);

CREATE TABLE clientes (
    cliente_id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grp_id                  INTEGER REFERENCES grupos_econ(grp_id),
    cliente_nome            TEXT NOT NULL,
    cliente_cnpj            TEXT,
    cliente_cnpj_fat        TEXT,
    cliente_cnpj_number     TEXT,
    cliente_status          TEXT DEFAULT 'INATIVO', -- mantido por TRIGGER (ver triggers.pg.sql)
    cliente_dat_bloqueio    TEXT,
    cliente_dia_venc_consumo    INTEGER,
    cliente_dia_venc_carteira   INTEGER,
    cliente_cod_github      TEXT,
    cliente_log             TEXT,
    cliente_tip_vlr         TEXT
);
CREATE INDEX idx_clientes_status ON clientes(cliente_status);
CREATE INDEX idx_clientes_grp ON clientes(grp_id);

CREATE TABLE pessoas (
    pessoa_id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pessoa_nome         TEXT NOT NULL,
    pessoa_status       TEXT,
    pessoa_funcao       TEXT,
    pessoa_grupo        TEXT GENERATED ALWAYS AS (
        CASE
            WHEN position(' ' IN pessoa_funcao) = 0 THEN 'T'
            WHEN upper(substring(pessoa_funcao FROM 1 FOR position(' ' IN pessoa_funcao) - 1)) = 'GERENTE' THEN 'G'
            WHEN upper(substring(pessoa_funcao FROM 1 FOR position(' ' IN pessoa_funcao) - 1)) = 'COORDENADOR' THEN 'L'
            WHEN upper(substring(pessoa_funcao FROM 1 FOR position(' ' IN pessoa_funcao) - 1)) = 'LIDER' THEN 'L'
            WHEN upper(substring(pessoa_funcao FROM 1 FOR position(' ' IN pessoa_funcao) - 1)) = 'DIRETOR' THEN 'D'
            ELSE 'T'
        END
    ) STORED,
    pessoa_mail         TEXT,
    pessoa_fone         TEXT,
    pessoa_whatsapp     TEXT GENERATED ALWAYS AS (
        CASE WHEN pessoa_fone IS NOT NULL AND pessoa_fone <> ''
            THEN 'wa.me/' || replace(replace(replace(replace(replace(
                    pessoa_fone, '.', ''), ' ', ''), '-', ''), ')', ''), '(', '')
            ELSE ''
        END
    ) STORED,
    pessoa_diretor      INTEGER REFERENCES pessoas(pessoa_id),
    pessoa_ger_exec     INTEGER REFERENCES pessoas(pessoa_id),
    pessoa_ger          INTEGER REFERENCES pessoas(pessoa_id),
    pessoa_lider        INTEGER REFERENCES pessoas(pessoa_id),
    pessoa_squad        TEXT,
    pessoa_billable     TEXT
);
CREATE INDEX idx_pessoas_lider ON pessoas(pessoa_lider);

CREATE TABLE ferias_marcacao (
    feriasm_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pessoa_id       INTEGER NOT NULL REFERENCES pessoas(pessoa_id),
    feriasm_tipo    TEXT NOT NULL,
    feriasm_indice  INTEGER GENERATED ALWAYS AS (
        CASE feriasm_tipo WHEN 'FERIAS' THEN 1 WHEN 'RECESSO' THEN 2 WHEN 'LICENÇA' THEN 3 END
    ) STORED,
    feriasm_ini     TEXT NOT NULL,
    feriasm_fim     TEXT NOT NULL,
    -- feriasm_prazo NÃO é coluna gerada aqui (diferente do original SQLite): o cast texto->date
    -- (`::date`) que a fórmula original (julianday) precisaria não é IMMUTABLE no Postgres
    -- (depende do DateStyle da sessão), então o Postgres recusa usá-lo numa coluna GENERATED.
    -- Computar em código de aplicação no handler de ferias_marcacao (mesma solução já usada
    -- pra cart_nome_plan_analitica, ver comentário lá).
    feriasm_prazo   INTEGER
);
CREATE INDEX idx_feriasm_pessoa ON ferias_marcacao(pessoa_id);
CREATE INDEX idx_feriasm_periodo ON ferias_marcacao(feriasm_ini, feriasm_fim);

CREATE TABLE produtos (
    produto_id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produto_area            TEXT,
    produto_nome            TEXT NOT NULL,
    produto_detalhe         TEXT,
    produto_suite           TEXT,
    produto_tip_apuracao    TEXT,
    produto_sku             TEXT,
    produto_franquia        TEXT,
    produto_grupo           INTEGER,
    produto_preco           NUMERIC(14,2),
    produto_recorrencia     TEXT,
    produto_regra_apuracao  TEXT
);

CREATE TABLE servidores (
    server_id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    server_nome         TEXT NOT NULL,
    server_ambiente      TEXT,
    server_finalidade    TEXT,
    server_mysql         TEXT,
    server_status        TEXT,
    server_proc          TEXT,
    server_conteudo      TEXT,
    server_familia       TEXT
);

CREATE TABLE list_resp_crono (
    resp_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resp_nome  TEXT NOT NULL
);

-- ============================================================
-- TABELAS OPERACIONAIS
-- ============================================================

CREATE TABLE urls (
    url_id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id          INTEGER NOT NULL REFERENCES clientes(cliente_id),
    url_path            TEXT NOT NULL,
    server_id           INTEGER REFERENCES servidores(server_id),
    produto_id          INTEGER REFERENCES produtos(produto_id),
    url_status          TEXT,
    url_dt_status        TEXT,
    url_exc              TEXT,
    url_dt_exc           TEXT,
    url_pasta_raiz       TEXT,
    url_pasta_anexos     TEXT,
    urb_bd               TEXT,
    url_obs              TEXT
);
CREATE INDEX idx_urls_cliente ON urls(cliente_id);
CREATE INDEX idx_urls_status ON urls(url_status);

CREATE TABLE contatos (
    contato_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id       INTEGER NOT NULL REFERENCES clientes(cliente_id),
    contato_nome     TEXT NOT NULL,
    contato_mail     TEXT,
    contato_fone     TEXT,
    contato_status   TEXT
);
CREATE INDEX idx_contatos_cliente ON contatos(cliente_id);

CREATE TABLE cart_mes (
    cart_mes_id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_ano_mes         TEXT NOT NULL,
    cart_vigencia_ativa  TEXT
);

CREATE TABLE precos_cliente (
    pc_id                       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id                  INTEGER NOT NULL REFERENCES clientes(cliente_id),
    produto_id                  INTEGER NOT NULL REFERENCES produtos(produto_id),
    cart_mes_id                 INTEGER REFERENCES cart_mes(cart_mes_id),
    pc_dat_niver                TEXT,
    pc_cod_index                TEXT,
    pc_vlr_franquia             NUMERIC(14,2),
    pc_vlr_unit                 NUMERIC(14,4) DEFAULT 2.06,
    pc_fx1_lim NUMERIC(14,2), pc_fx2_lim NUMERIC(14,2), pc_fx3_lim NUMERIC(14,2),
    pc_fx4_lim NUMERIC(14,2), pc_fx5_lim NUMERIC(14,2),
    pc_fx1_vlr NUMERIC(14,2), pc_fx2_vlr NUMERIC(14,2), pc_fx3_vlr NUMERIC(14,2),
    pc_fx4_vlr NUMERIC(14,2), pc_fx5_vlr NUMERIC(14,2)
);
CREATE INDEX idx_pc_cliente ON precos_cliente(cliente_id);
CREATE INDEX idx_pc_produto ON precos_cliente(produto_id);

CREATE TABLE consumo_ana (
    consumo_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id      INTEGER NOT NULL REFERENCES clientes(cliente_id),
    produto_id      INTEGER NOT NULL REFERENCES produtos(produto_id),
    cart_mes_id     INTEGER REFERENCES cart_mes(cart_mes_id),
    consumo_data    TEXT NOT NULL,
    consumo_qtd     NUMERIC(14,4),
    consumo_det     TEXT,
    consumo_consit  TEXT
);
CREATE INDEX idx_consumo_cliente_produto_mes ON consumo_ana(cliente_id, produto_id, cart_mes_id);
CREATE INDEX idx_consumo_data ON consumo_ana(consumo_data);

CREATE TABLE faturamento (
    fat_id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_mes_id             INTEGER REFERENCES cart_mes(cart_mes_id),
    cliente_id              INTEGER NOT NULL REFERENCES clientes(cliente_id),
    fat_dat_venc            TEXT,
    fat_cod_venc_protheus   TEXT,
    fat_num_nfe             TEXT,
    fat_num_rps             TEXT,
    fat_obs                 TEXT
);
CREATE INDEX idx_faturamento_cliente ON faturamento(cliente_id);

CREATE TABLE carteira (
    cart_id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id              INTEGER NOT NULL REFERENCES clientes(cliente_id),
    cart_mes_id             INTEGER REFERENCES cart_mes(cart_mes_id),
    cart_qtd                INTEGER,
    cart_vlr                NUMERIC(14,2),
    cart_pdd                NUMERIC(14,2),
    cart_sem_pdd             NUMERIC(14,2),
    cart_fat                NUMERIC(14,2),
    cart_qtd_mes            INTEGER,
    cart_emprestimos_mes    INTEGER,
    cart_ult_def            TEXT,
    cart_data_base          TEXT,
    cart_dat_extracao       TEXT,
    cart_rds                TEXT,
    cart_db                 TEXT,
    cart_prod               TEXT,
    -- cart_nome_plan_analitica: no original (SQLite) usava strftime(); aqui, como
    -- cart_data_base já é TEXT em formato ISO (YYYY-MM-DD), a mesma extração é feita com
    -- substring/concatenação puros (IMMUTABLE), sem precisar de to_char/data real -- isso evita
    -- o problema de to_char não ser IMMUTABLE (dependente de locale) e mantém a coluna
    -- declarativa, sem precisar virar lógica de aplicação.
    cart_nome_plan_analitica TEXT GENERATED ALWAYS AS (
        cart_prod || '_Medicao_' ||
        substring(cart_data_base FROM 1 FOR 7) || '-01_' ||
        substring(cart_data_base FROM 1 FOR 7) || '-' || substring(cart_data_base FROM 9 FOR 2) || '.xlsx'
    ) STORED,
    cart_url_plan_analitica  TEXT
);
CREATE INDEX idx_carteira_cliente_mes ON carteira(cliente_id, cart_mes_id);

CREATE TABLE resp (
    resp_id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id      INTEGER NOT NULL REFERENCES clientes(cliente_id),
    resp_tipo       TEXT,
    pessoa_id       INTEGER REFERENCES pessoas(pessoa_id)
);
CREATE INDEX idx_resp_cliente ON resp(cliente_id);

CREATE TABLE escala (
    escala_id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pessoa_id        INTEGER NOT NULL REFERENCES pessoas(pessoa_id),
    escala_data      TEXT NOT NULL,
    escala_hora_ini  TEXT,
    escala_hora_fim  TEXT
);
CREATE INDEX idx_escala_pessoa_data ON escala(pessoa_id, escala_data);

CREATE TABLE portfolios (
    port_id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id      INTEGER NOT NULL REFERENCES clientes(cliente_id),
    port_tipo       TEXT,
    port_nome       TEXT,
    port_pm         TEXT,
    port_diretorio  TEXT,
    port_status     TEXT,
    port_pdf        INTEGER
);
CREATE INDEX idx_portfolios_cliente ON portfolios(cliente_id);

CREATE TABLE crono (
    crono_id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    port_id             INTEGER NOT NULL REFERENCES portfolios(port_id),
    crono_grupo         INTEGER,
    crono_topico        INTEGER,
    crono_grp_tpc       TEXT GENERATED ALWAYS AS (
        crono_grupo::text || CASE WHEN crono_topico IS NULL OR crono_topico = 0 THEN '' ELSE '.' || crono_topico::text END
    ) STORED,
    crono_tipo          TEXT,
    crono_atividade     TEXT,
    crono_inicio        TEXT,
    crono_fim           TEXT,
    crono_replan        TEXT,
    crono_esforco       TEXT,
    crono_perc_atual    NUMERIC(6,4),
    crono_hh_orc        NUMERIC(10,2),
    crono_hh_real       NUMERIC(10,2),
    crono_status        TEXT,
    resp_id             INTEGER REFERENCES list_resp_crono(resp_id),
    crono_demanda_1     TEXT,
    crono_demanda_2     TEXT,
    crono_demanda_3     TEXT,
    crono_relat         INTEGER
);
CREATE INDEX idx_crono_port_grupo ON crono(port_id, crono_grupo);

CREATE TABLE propostas (
    proposta_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id        INTEGER NOT NULL REFERENCES clientes(cliente_id),
    proposta_chamado  INTEGER,
    proposta_demanda  INTEGER,
    proposta_nome     TEXT,
    proposta_desc     TEXT,
    proposta_hh       NUMERIC(10,2),
    proposta_vlr      NUMERIC(14,2),
    proposta_status   TEXT,
    proposta_anexo    TEXT
);
CREATE INDEX idx_propostas_cliente ON propostas(cliente_id);

CREATE TABLE fornecedores (
    fornecedor_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fornecedor_area    TEXT,
    fornecedor_nome    TEXT NOT NULL,
    fornecedor_cnpj    TEXT
);

CREATE TABLE forn_contratos (
    forn_cont_id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fornecedor_id           INTEGER NOT NULL REFERENCES fornecedores(fornecedor_id),
    pessoa_id               INTEGER REFERENCES pessoas(pessoa_id),
    forn_cont_num_contrato  TEXT,
    forn_cont_tipo          TEXT,
    forn_cont_nivel         TEXT,
    forn_cont_aloc          TEXT,
    forn_cont_qtd_prf       INTEGER,
    forn_cont_desc          TEXT,
    forn_cont_tip_vlr       TEXT,
    forn_cont_vlr_mes       NUMERIC(14,2),
    forn_cont_dt_ini        TEXT,
    forn_cont_dt_fim        TEXT,
    forn_cont_ind_reaj      TEXT,
    forn_cont_status        TEXT
);
CREATE INDEX idx_forncont_fornecedor ON forn_contratos(fornecedor_id);

CREATE TABLE forn_pagadoria (
    forn_pag_id                     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fornecedor_id                   INTEGER NOT NULL REFERENCES fornecedores(fornecedor_id),
    forn_pag_resp                   TEXT,
    forn_pag_tipo                   TEXT,
    forn_pag_tipo_detalhado         TEXT,
    forn_pag_competencia            TEXT,
    forn_pag_dat                    TEXT,
    forn_pag_nome_prf               TEXT,
    forn_pag_qtd                    NUMERIC(14,4),
    forn_pag_vlr_unit               NUMERIC(14,2),
    forn_pag_tot_bruto              NUMERIC(14,2),
    forn_pag_tot_liq                NUMERIC(14,2),
    forn_pag_vlr_pag_cliente_bruto  NUMERIC(14,2),
    forn_pag_vlr_pag_cliente_liq    NUMERIC(14,2),
    forn_pag_vlr_receita_bruta      NUMERIC(14,2),
    forn_pag_vlr_receita_liq        NUMERIC(14,2),
    forn_pag_obs                    TEXT
);
CREATE INDEX idx_fornpag_fornecedor ON forn_pagadoria(fornecedor_id);

CREATE TABLE anexos (
    anexo_id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id      INTEGER REFERENCES clientes(cliente_id),
    fornecedor_id   INTEGER REFERENCES fornecedores(fornecedor_id),
    anexo_nome      TEXT,
    anexo_data      TEXT,
    anexo_arquivo   TEXT
);

CREATE TABLE parametros_gerais (
    -- linha única fixa (id sempre 1) -- não usa IDENTITY, nunca é auto-gerado
    param_id                INTEGER PRIMARY KEY CHECK (param_id = 1),
    param_logo_escuro_url   TEXT,
    param_logo_claro_url    TEXT
);
INSERT INTO parametros_gerais (param_id) VALUES (1);

-- ============================================================
-- REFERÊNCIA / ENUM (tabelas pequenas, listas fixas)
-- ============================================================

CREATE TABLE usuarios (
    user_id                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_nome                  TEXT NOT NULL,
    -- citext: comparação/unicidade já nativamente case-insensitive, substitui o
    -- COLLATE NOCASE usado nas queries de auth.ts/usuarios.ts.
    user_mail                  CITEXT NOT NULL UNIQUE,
    user_status                TEXT,
    user_senha_hash             TEXT,
    user_deve_trocar_senha      INTEGER NOT NULL DEFAULT 1,
    user_convite_token          TEXT,
    user_convite_expira_em      TEXT
);

CREATE TABLE usuario_sessoes (
    sessao_token  TEXT PRIMARY KEY,
    user_id       INTEGER NOT NULL REFERENCES usuarios(user_id) ON DELETE CASCADE,
    criado_em     TEXT NOT NULL,
    expira_em     TEXT NOT NULL
);
CREATE INDEX idx_usuario_sessoes_user ON usuario_sessoes(user_id);

CREATE TABLE usuarios_permissoes_menu (
    user_id        INTEGER NOT NULL REFERENCES usuarios(user_id),
    menu_key       TEXT NOT NULL,
    perm_leitura   INTEGER NOT NULL DEFAULT 0,
    perm_insercao  INTEGER NOT NULL DEFAULT 0,
    perm_edicao    INTEGER NOT NULL DEFAULT 0,
    perm_exclusao  INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (user_id, menu_key)
);

CREATE TABLE list_tip_resp (
    tip_resp   TEXT PRIMARY KEY
);

CREATE TABLE list_url_status (
    url_status  TEXT PRIMARY KEY
);

CREATE TABLE indices_economicos (
    index_cod   INTEGER,
    index_nome  TEXT NOT NULL,
    index_ano   INTEGER NOT NULL,
    index_mes   INTEGER NOT NULL,
    index_vlr   NUMERIC(10,4),
    PRIMARY KEY (index_nome, index_ano, index_mes)
);
