-- Cria a tabela de PREPARO usada pela importação de consumo (Admin > Importar Consumo).
-- Não é parte do modelo de domínio -- é um degrau técnico pra contornar o limite de tamanho de
-- requisição da Vercel (~4.5MB): arquivos reais desse fluxo passam de 60 mil linhas, e um POST
-- só com tudo estoura esse limite ANTES de chegar no Express (o navegador mostra isso como erro
-- de CORS, porque a resposta de erro da própria Vercel não carrega o header de CORS -- achado
-- 2026-08-31). O navegador agora sobe os arquivos em lotes pequenos pra cá, e só depois a rota
-- de importação lê tudo daqui (consulta SQL, sem limite de tamanho de requisição HTTP) pra
-- classificar/gravar nas tabelas de verdade (consumo_ana/precos_cliente/faturamento). Sempre
-- limpa (por cart_mes_id) no início de uma nova sessão de upload e no fim de uma confirmação --
-- nunca deve reter dado entre uma importação e outra.

CREATE TABLE IF NOT EXISTS consumo_import_staging (
    staging_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_mes_id   INTEGER NOT NULL REFERENCES cart_mes(cart_mes_id),
    id_produto    TEXT,
    cnpj          TEXT,
    data          TEXT,
    quantidade    TEXT,
    detalhamento  TEXT
);
CREATE INDEX IF NOT EXISTS idx_consumo_staging_mes ON consumo_import_staging(cart_mes_id);

-- conferência
SELECT COUNT(*) AS linhas_na_tabela_nova FROM consumo_import_staging;
