-- Reajuste de preço de consumo -- tabela de histórico + view de exibição (idempotente)

CREATE TABLE IF NOT EXISTS reajuste_eventos (
    reaj_id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pc_id                   INTEGER NOT NULL REFERENCES precos_cliente(pc_id) ON DELETE CASCADE,
    cliente_id              INTEGER NOT NULL REFERENCES clientes(cliente_id),
    produto_id              INTEGER NOT NULL REFERENCES produtos(produto_id),
    reaj_data                TEXT NOT NULL,
    reaj_index_nome          TEXT NOT NULL,
    reaj_index_ano           INTEGER NOT NULL,
    reaj_index_mes           INTEGER NOT NULL,
    reaj_taxa_acum_12m       NUMERIC(10,6) NOT NULL,
    reaj_vlr_unit_ant        NUMERIC(14,4),
    reaj_vlr_unit_novo       NUMERIC(14,4),
    reaj_vlr_franquia_ant    NUMERIC(14,2),
    reaj_vlr_franquia_novo   NUMERIC(14,2)
);

CREATE INDEX IF NOT EXISTS idx_reaj_pc ON reajuste_eventos(pc_id);
CREATE INDEX IF NOT EXISTS idx_reaj_cliente ON reajuste_eventos(cliente_id);
CREATE INDEX IF NOT EXISTS idx_reaj_ano_mes ON reajuste_eventos(reaj_index_ano, reaj_index_mes);

CREATE OR REPLACE VIEW reajuste_eventos_detalhe AS
SELECT
    re.*,
    c.cliente_nome,
    c.cliente_cnpj,
    p.produto_nome,
    p.produto_detalhe
FROM reajuste_eventos re
JOIN clientes c ON c.cliente_id = re.cliente_id
JOIN produtos p ON p.produto_id = re.produto_id;

-- conferência
SELECT 'reajuste_eventos' AS tabela, COUNT(*) AS linhas FROM reajuste_eventos
UNION ALL
SELECT 'reajuste_eventos_detalhe', COUNT(*) FROM reajuste_eventos_detalhe;
